on: push

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: verify git repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install dependencies
        run: npm i

      - name: run jest
        run: npm run test
